package example2.org.seasar.lucene.dto;

import java.math.BigDecimal;

import org.seasar.dao.annotation.tiger.Bean;
import org.seasar.dao.annotation.tiger.Id;
import org.seasar.lucene.annotation.LuceneDto;
import org.seasar.lucene.annotation.LuceneField;
import org.seasar.lucene.annotation.LuceneId;

@LuceneDto(typeName = "Documents")
@Bean(table = "Documents")
public class DocumentsDto {

	@LuceneId
	@LuceneField(fieldName = "id", store = true, toknize = false, analyzerType = "standard")
	@Id(sequenceName = "DocumensId")
	private long id;

	@LuceneField(fieldName = "name", store = false, toknize = true, analyzerType = "Japanese")
	private String name;

	@LuceneField(fieldName = "category", store = false, toknize = true, analyzerType = "Japanese")
	private String category;

	private BigDecimal price;

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getCategory() {
		return category;
	}

	public void setCategory(String category) {
		this.category = category;
	}

	public BigDecimal getPrice() {
		return price;
	}

	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * @generated by CodeSugar http://sourceforge.net/projects/codesugar
	 */

	public String toString() {
		StringBuffer buffer = new StringBuffer();
		buffer.append("[DocumentsDto:");
		buffer.append(" id: ");
		buffer.append(id);
		buffer.append(" name: ");
		buffer.append(name);
		buffer.append(" category: ");
		buffer.append(category);
		buffer.append(" price: ");
		buffer.append(price);
		buffer.append("]");
		return buffer.toString();
	}

}
